# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
#    config.vm.box = "cosm/centos7_ruby2.4"
    config.vm.box = "debian/buster64"

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "gl-exporter"
    end

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
    end

end

