# -*- mode: ruby -*-
# vi: set ft=ruby :

#BOX_IMAGE = "hashicorp/precise64"
BOX_IMAGE = "debian/bullseye64"
NIC = "wlp3s0"
PROVIDER = "virtualbox"

Vagrant.configure("2") do |config|
    config.vm.define "testes" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "ansible"
        subconfig.vm.network :public_network, ip: "192.168.1.100", bridge: NIC

        subconfig.ssh.forward_agent = true

        subconfig.vm.synced_folder ".", "/vagrant"
        subconfig.vm.synced_folder "/home/btoll/dotfiles", "/vagrant/dotfiles"

        subconfig.vm.provider PROVIDER do |v|
            v.cpus = 4
            v.gui = false
            v.memory = 8192
            v.name = "ansible"
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
        # Fixes the "-bash: warning: setlocale: LC_ALL: cannot change locale (en_IN.UTF-8)" warning.
        # Also, fixes the same warnings for Perl.
        localedef -i en_US -f UTF-8 en_US.UTF-8
    SHELL

    config.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yml"
        ansible.install_mode = "default"
    end
end

