# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://docs.bazel.build/versions/4.2.1/install-ubuntu.html

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "bazel"
    end

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
    end
end

