# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provision "shell", inline: <<-SHELL
        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        apt-get update
        apt-get install -y nomad

        # Install Docker Community Edition
        echo "Docker Install Beginning..."
        apt-get remove docker docker-engine docker.io
        apt-get install apt-transport-https ca-certificates curl software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg |  sudo apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        apt-get update -y
        apt-get install -y docker-ce
        service docker restart
        # Configure Docker to be run as the vagrant user
        usermod -aG docker vagrant
        docker --version
    SHELL
end

