# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network :forwarded_port, guest: 3000, host: 3000

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "billing"
    end

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
        s.env = {
            JFROG_USERNAME:ENV["JFROG_USERNAME"],
            JFROG_PASSWORD:ENV["JFROG_PASSWORD"]
        }
    end
end

