# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.ssh.forward_agent = true

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
        s.env = {
            JFROG_USERNAME:ENV["JFROG_USERNAME"],
            JFROG_PASSWORD:ENV["JFROG_PASSWORD"]
        }
    end
end

