# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "ipc-course"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y build-essential cscope git tmux vim
        git clone http://github.com/csepracticals/serverdesign
        cd serverdesign
    SHELL
end

