# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "terraform"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y curl gnupg software-properties-common unzip

        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        apt-get update
        apt-get install terraform
        #terraform -install-autocomplete

        # Install Docker Community Edition.
        apt-get install -y \
            apt-transport-https \
            ca-certificates \
            software-properties-common

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        apt-get update
        apt-get install -y docker-ce
        service docker restart
        usermod -aG docker vagrant

        # Install Docker Compose.
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

        # Install AWS CLI.
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install

        # Install Consul.
#        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
#        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#        apt-get update
#        apt-get install consul

        # Fixes the "-bash: warning: setlocale: LC_ALL: cannot change locale (en_IN.UTF-8)" warning.
        {
            echo LANG=en_US.utf-8 ;
            echo LC_ALL=en_US.utf-8 ;
        } >> /etc/environment
    SHELL
end

