# -*- mode: ruby -*-
# vi: set ft=ruby :

#export AWS_DEFAULT_REGION=us-west-2
#export AWS_SECRET_ACCESS_KEY=
#export AWS_ACCESS_KEY_ID=
#export TF_VAR_key_name=cloudacademy
#export TF_VAR_workstation_ip=47.14.76.104/32

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "vagrant-terraform"

    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "/home/btoll/dotfiles", "/vagrant/dotfiles"

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = 8192
        vb.name = "terraform"
    end

    config.vm.provision "shell", inline: <<-SHELL
        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        wget -O- https://apt.releases.hashicorp.com/gpg \
            | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

        echo "deb \
            [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
            https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
            | > /etc/apt/sources.list.d/hashicorp.list

        apt update && \
        apt install -y \
            curl \
            terraform

        #terraform -install-autocomplete

        # Fixes the "-bash: warning: setlocale: LC_ALL: cannot change locale (en_IN.UTF-8)" warning.
        {
            echo LANG=en_US.utf-8 ;
            echo LC_ALL=en_US.utf-8 ;
        } >> /etc/environment
    SHELL

    config.vm.provision :ansible_local do |ansible|
        ansible.become = true
        ansible.groups = {
            "servers" => ["default"]
        }

        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yml"
        ansible.version = "latest"
        ansible.extra_vars = {
            ansible_python_interpreter: "/usr/bin/python3"
        }
        ansible.galaxy_roles_path = nil
        ansible.galaxy_role_file = "requirements.yml"
        ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}"
    end
end

