# sudo apt-get install apache2-utils
# htpasswd -nBC 12 "" | tr -d ":\n"
#
# password=foobar

tls_server_config:
  cert_file: node_exporter.crt
  key_file: node_exporter.key
basic_auth_users:
  prometheus: $2y$12$rHsz57FebjOyLQ1WE0.51uwcm03eWcYrsNaFJj8vL4qnUnoHRsaXa
