# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # The `focal` image is throwing an exception, temporarily use `bionic`.
    config.vm.box = "ubuntu/bionic64"
    config.vm.network :forwarded_port, guest: 3000, host: 3000

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "docker-compose"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y \
            build-essential \
            curl \
            git \
            libmysqlclient-dev \
            libreadline-dev \
            libssl-dev \
            zlib1g-dev

        # Install Docker Community Edition.
        apt-get install -y \
            apt-transport-https \
            ca-certificates \
            software-properties-common

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        apt-get update
        apt-get install -y docker-ce
        service docker restart
        usermod -aG docker vagrant

        # Install Docker Compose.
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    SHELL
end

