# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "vagrant-charmed"

#    config.vm.network "forwarded_port", guest: 80, host: 8080
#    config.vm.network "private_network", ip: "192.168.33.10"
#    config.vm.network "public_network", ip: "192.168.1.53", bridge: "wlp3s0"

    config.vm.synced_folder ".", "/vagrant"
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 4
        vb.gui = false
        vb.memory = 8192
        vb.name = "charmed"
    end

#    config.vm.provision :shell do |s|
#        s.path = "scripts/root.sh"
#        s.env = {
#            USER:ENV["USER"],
#        }
#    end

    config.vm.provision "shell", inline: <<-SHELL
        add-apt-repository ppa:deadsnakes/ppa && \
        apt-get update && \
        apt-get install -y \
            build-essential \
            curl \
            git \
            gnupg2 \
            python3.9 \
            software-properties-common \
            wget

        update-alternatives --install /usr/bin/python python /usr/bin/python3.9 2
        # https://bugs.launchpad.net/juju/+bug/1995697
        # sudo mkdir -p ~/.local/share

        # Fixes the "-bash: warning: setlocale: LC_ALL: cannot change locale (en_IN.UTF-8)" warning.
        # Also, fixes the same warnings for Perl.
        localedef -i en_US -f UTF-8 en_US.UTF-8
    SHELL

    config.vm.provision :ansible_local do |ansible|
        ansible.become = true
        ansible.groups = {
            "servers" => ["default"]
        }

        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yml"
        ansible.version = "latest"
        ansible.extra_vars = {
            ansible_python_interpreter: "/usr/bin/python3"
        }
        ansible.galaxy_roles_path = nil
        ansible.galaxy_role_file = "requirements.yml"
        ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}"
    end
end

