# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#    config.vm.box = "centos/7"
    config.vm.box = "ubuntu/focal64"

    config.vm.provision "shell", inline: <<-SHELL
#        yum install install git -y
        apt-get update
        apt-get install git -y
        git clone https://github.com/btoll/dotfiles.git
    SHELL
end

