# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.network :forwarded_port, host: 4141, guest: 4141

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.name = "test"
    end

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
        s.env = {
            USER:ENV["USER"],
            GITHUB_TOKEN:ENV["GITHUB_TOKEN"],
            GITHUB_USER:ENV["GITHUB_USER"],
            GIT_HOST:ENV["GIT_HOST"],
            GITHUB_REPO:ENV["GITHUB_REPO"],
        }
    end

    config.ssh.forward_agent = true
end

