apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        #        - 10.8.8.100-10.8.8.110
        - 192.168.49.200-192.168.49.210

