# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#    config.vm.box = "ubuntu/focal64"
    config.vm.box = "bento/ubuntu-21.10"
    config.ssh.forward_x11 = "false"

    config.vm.provision "shell", inline: <<-SHELL
        # Install Ruby and its REPL.
        apt-get update
        apt-get install -y ruby-full pry

        # Install Docker Community Edition.
        apt-get install -y \
            apt-transport-https \
            ca-certificates \
            software-properties-common

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        apt-get update
        apt-get install -y docker-ce
        service docker restart
        usermod -aG docker vagrant

        # Install VS Code.
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- \
            | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        apt-get update
        apt-get install -y \
            code \
            libasound2 \
            libxshmfence1

#        curl -Lo code_1.64.2-1644445741_amd64.deb \
#            https://update.code.visualstudio.com/1.64.2/linux-deb-x64/stable
#        dpkg -i code_1.64.2-1644445741_amd64.deb -y
#        # Install dependencies.
#        apt-get install -f
    SHELL
end

