# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "nginx"
    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.name = "nginx"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y \
            git \
            nginx

        git clone https://github.com/btoll/italy
    SHELL
end

