# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 8080, host: 8080

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 2
        vb.memory = 4096
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y openjdk-11-jdk
        cp /var/lib/jenkins/secrets/initialAdminPassword /vagrant
        # 192.168.33.10:8080/login

        wget -O /usr/share/keyrings/jenkins-keyring.asc \
            https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
            https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
            /etc/apt/sources.list.d/jenkins.list > /dev/null

        apt-get update
        apt-get install -y jenkins
    SHELL
end

