# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "github"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.name = "github"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y \
            git \
            ruby-full

        git clone https://github.com/github-developer/github-app-template.git
    SHELL
end

