# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # The `focal` image is throwing an exception, temporarily use `bionic`.
    config.vm.box = "ubuntu/bionic64"

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "node"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y \
            curl \
            git

        # https://github.com/nodesource/distributions/blob/master/README.md#debinstall
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
    SHELL
end

