apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: beta
nodes:
- role: control-plane
- role: worker
  labels:
    zone: 1
- role: worker
  labels:
    zone: 2
- role: worker
  labels:
    zone: 3
- role: worker
  labels:
    zone: 4

