# first: `k create sa brownie`

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: brownie-secret
  annotations:
    kubernetes.io/service-account.name: brownie

# this secret will create a non-expiry token
# run: `k describe sa brownie`

