# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.ssh.forward_agent = true

    config.vm.post_up_message = <<-MSG
        Configure the runner (only need to do this once):
        $ cd actions-runner
        $ ./config.sh --url https://github.com/YOUR_REPOSITORY --token YOUR_TOKEN

        Start the runner:
        $ cd actions-runner
        $ ./run.sh

        For more information:
        https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
    MSG

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.name = "action-runner"
    end

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
    end
end

