# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.name = "babel"
    end

    config.vm.provision :shell do |s|
        s.path = "scripts/root.sh"
    end
end

